project:
  type: website
  output-dir: docs

website:
  title: "Practice Portfolio for CWD"
  navbar:
    foreground: "lavender"
    background: "purple"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  search: true
  twitter-card:
    creator: "@PieRatio"

format:
  html:
    theme:
       light: flatly
       dark: darkly    
    css: styles.css
    toc: true




